SecurityInAOMG/Controllers/GroupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SecurityInAOMG.Models;
using System.Data.SqlClient;

namespace SecurityInAOMG.Controllers
{
    public class GroupController : Controller
    {
       
        SqlConnection con = new db().con;
        
        // GET: Group
       
        public ActionResult Index()
        {
            if (Session["user"] != null)
            {
                List<UserAccount> model = new db().GetUserAccount();
                return View(model);
            }else
            {
                return Redirect("https://localhost:44357/");
            }
           
        }

        public ActionResult Edit(int id)
        {
            List<UserAccount> userList = new db().GetUserAccount();
            var getId = userList.Single(m => m.userId == id);
         
            return View(getId);
        }

        [HttpPost]
        public ActionResult Edit(UserAccount user, int id)
        {
            
            SqlCommand cmd = new SqlCommand();


            List<UserAccount> userList = new db().GetUserAccount();
            var getId = userList.Single(m => m.userId == id);
            
            con.Open();

            try
            {

                cmd.CommandText = "update Users set password='" + user.password + "' , roles='" + user.roles + "' where userID= " + getId.userId + "";
                cmd.Connection = con;
                cmd.ExecuteNonQuery();
            }catch(Exception e)
            {
                Console.WriteLine(e.Message);
            }
            finally
            {
                con.Close();

            }
           
            return View();

        }
       
    }
}

SecurityInAOMG/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SecurityInAOMG.Models;
using System.Data.SqlClient;
using System.Data;
using System.Dynamic;

namespace SecurityInAOMG.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {

          

            db showData = new db();
            DataSet ds = showData.GetArtistData();
          
            if (Session["user"] != null && (int)Session["user"] == 1)
            {
                // int VIPNumber = (int)Session["user"];
                ViewBag.data = ds.Tables[0];
                return View("adminView");

            }
            else if(Session["user"] != null && (int)Session["user"] == 2)
            {
                ViewBag.data = ds.Tables[0];
                return View("userView");
            }
            else if (Session["user"] !=null && (int)Session["user"] == 3)
            {

                db data = new db();
                dynamic mymodel = new ExpandoObject();
                mymodel.RolesGroup = data.GetUserGroup();
                mymodel.ArtistData = data.GetArtistDataNormal();

                return View("editorView", mymodel);
            }

          
            else
            {
                return View("Index");
            }


        }










    }
}

SecurityInAOMG/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.SqlClient;
using SecurityInAOMG.Models;

namespace SeurityASP.NET.Controllers
{
    public class LoginController : Controller
    {
        SqlConnection con = new db().con;
        SqlCommand cmd1 = new SqlCommand();
        SqlCommand cmd2 = new SqlCommand();
        SqlCommand cmd3 = new SqlCommand();
        SqlDataReader dr;
        SqlDataReader dr2;
        SqlDataReader dr3;
        // GET: Login
        public ActionResult Index()
        {
            if (Session["user"] != null)
            {
                Response.Redirect("https://www.google.com.vn/imghp?hl=vi");

            }

            return View();
        }

        public JsonResult CheckLogin(FormCollection Collection)
        {
            string uid = Collection["uid"];
            string pwd = Collection["password"];



            cmd1.Connection = con;
            cmd2.Connection = con;
            cmd3.Connection = con;

            con.Open();

            cmd1.CommandText = "select * from Users where username= @uid and password=@pwd  and roles=@roles ";
            cmd1.Parameters.AddWithValue("@uid", uid);
            cmd1.Parameters.AddWithValue("@pwd", pwd);
            cmd1.Parameters.AddWithValue("@roles", "admin");


            cmd2.CommandText = "select * from Users where username= @uid and password=@pwd  and roles=@roles ";
            cmd2.Parameters.AddWithValue("@uid", uid);
            cmd2.Parameters.AddWithValue("@pwd", pwd);
            cmd2.Parameters.AddWithValue("@roles", "user");

            cmd3.CommandText = "select * from Users where username= @uid and password=@pwd  and roles=@roles ";
            cmd3.Parameters.AddWithValue("@uid", uid);
            cmd3.Parameters.AddWithValue("@pwd", pwd);
            cmd3.Parameters.AddWithValue("@roles", "editor");





            dr = cmd1.ExecuteReader();
            dr2 = cmd2.ExecuteReader();
            dr3 = cmd3.ExecuteReader();


            JsonResult jr = new JsonResult();

            if (dr.Read())
            {

                Session["user"] = 1;
                Session.Timeout = 5;

                jr.Data = new
                {
                    status = "OK"
                };
                con.Close();

            }
            else if (dr2.Read())
            {
                Session["user"] = 2;
                Session.Timeout = 5;

                jr.Data = new
                {
                    status = "OK"
                };


            }

            else if (dr3.Read())
            {
                Session["user"] = 3;
                Session.Timeout = 5;

                jr.Data = new
                {
                    status = "OK"
                };


            }
            else
            {
                jr.Data = new
                {
                    status = "False"
                };
            }

            return Json(jr, JsonRequestBehavior.AllowGet);


        }


        public ActionResult Logout()
        {
            Session.Clear();//remove session
            return RedirectToAction("Index");
        }





    }
}

SecurityInAOMG/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>

    <p>I'm Jayson</p>
     
</div>

SecurityInAOMG/Views/Home/adminView.cshtml
@model IEnumerable<SecurityInAOMG.Models.Artist>

@{
    Layout = "~/Views/Shared/_View.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>IndexLogin</title>
</head>
<body>
    <p>
        @Html.ActionLink("Resgister", "Resgister", "Resgister")
    </p>

    <p>
        @Html.ActionLink("Group User", "Index", "Group")
    </p>

    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Artist_Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Artist_role)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Artist_contact)
            </th>
            <th></th>
        </tr>

        @foreach (System.Data.DataRow dr  in ViewBag.data.Rows)
        {
            <tr>
                <td>
                 
                    @dr["Artist_Name"]
                </td>
                <td>
                
                    @dr["Artist_role"]
                </td>
                <td>
                  
                    @dr["Artist_contact"]
                </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                        @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                        @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                    </td>
                </tr>
            }

        </table>

        <a href="@Url.Action("Logout","Login")" class="btn btn-warning">Logout</a>
    </body>
    </html>

SecurityInAOMG/Views/Home/editorView.cshtml
@using SecurityInAOMG.Models;
@model dynamic

@{
    ViewBag.Title = "editorView";
    Layout = "~/Views/Shared/_View.cshtml";
}

<h2>editorView</h2>




<table class="table">
    <tr>
        <th>
            Artist Name
        </th>
        <th>
            Artist Role
        </th>
        <th>
            Artist Contact
        </th>
        <th></th>
    </tr>
    @foreach (UseGroup rolesProvider in Model.RolesGroup)
    {
        if (@rolesProvider.Editing == "Null" && @rolesProvider.Detail == "Detail" && @rolesProvider.Deleting == "Null")
        {
            foreach (Artist artist in Model.ArtistData)
            {
                <tr>
                    <td>

                        @artist.Artist_Name
                    </td>
                    <td>

                        @artist.Artist_role
                    </td>
                    <td>

                        @artist.Artist_contact
                    </td>
                    <td>

                        @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |

                    </td>
                </tr>

            }

        }
        else if (@rolesProvider.Editing == "" && @rolesProvider.Detail == 0 && @rolesProvider.Deleting == 0)
        {
            foreach (Artist artist in Model.ArtistData)
            {
                <tr>
                    <td>

                        @artist.Artist_Name
                    </td>
                    <td>

                        @artist.Artist_role
                    </td>
                    <td>

                        @artist.Artist_contact
                    </td>
                    <td>

                        @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |

                    </td>
                </tr>

            }

        }
        else if (@rolesProvider.Editing == 0 && @rolesProvider.Detail == 0 && @rolesProvider.Deleting == 1)
        {
            foreach (Artist artist in Model.ArtistData)
            {
                <tr>
                    <td>

                        @artist.Artist_Name
                    </td>
                    <td>

                        @artist.Artist_role
                    </td>
                    <td>

                        @artist.Artist_contact
                    </td>
                    <td>

                        @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ }) |

                    </td>
                </tr>

            }

        }
        else if (@rolesProvider.Editing == 1 && @rolesProvider.Detail == 1 && @rolesProvider.Deleting == 0)
        {
            foreach (Artist artist in Model.ArtistData)
            {
                <tr>
                    <td>

                        @artist.Artist_Name
                    </td>
                    <td>

                        @artist.Artist_role
                    </td>
                    <td>

                        @artist.Artist_contact
                    </td>
                    <td>

                        @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ })
                        @Html.ActionLink("Detail", "Detail", new { /* id=item.PrimaryKey */ })

                    </td>
                </tr>

            }

        }
        else if (@rolesProvider.Editing == 0 && @rolesProvider.Detail == 1 && @rolesProvider.Deleting == 1)
        {
            foreach (Artist artist in Model.ArtistData)
            {
                <tr>
                    <td>

                        @artist.Artist_Name
                    </td>
                    <td>

                        @artist.Artist_role
                    </td>
                    <td>

                        @artist.Artist_contact
                    </td>
                    <td>

                        @Html.ActionLink("Detail", "Detail", new { /* id=item.PrimaryKey */ })
                        @Html.ActionLink("Delete", "Detail", new { /* id=item.PrimaryKey */ })

                    </td>
                </tr>

            }

        }
        else if (@rolesProvider.Editing == 1 && @rolesProvider.Detail == 0 && @rolesProvider.Deleting == 1)
        {
            foreach (Artist artist in Model.ArtistData)
            {
                <tr>
                    <td>

                        @artist.Artist_Name
                    </td>
                    <td>

                        @artist.Artist_role
                    </td>
                    <td>

                        @artist.Artist_contact
                    </td>
                    <td>

                        @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ })
                        @Html.ActionLink("Delete", "Detail", new { /* id=item.PrimaryKey */ })

                    </td>
                </tr>

            }

        }
        else if (@rolesProvider.Editing == 1 && @rolesProvider.Detail == 1 && @rolesProvider.Deleting == 1)
        {
            foreach (Artist artist in Model.ArtistData)
            {
                <tr>
                    <td>

                        @artist.Artist_Name
                    </td>
                    <td>

                        @artist.Artist_role
                    </td>
                    <td>

                        @artist.Artist_contact
                    </td>
                    <td>

                        @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ })
                        @Html.ActionLink("Detail", "Detail", new { /* id=item.PrimaryKey */ })
                        @Html.ActionLink("Delete", "Detail", new { /* id=item.PrimaryKey */ })

                    </td>
                </tr>

            }

        }
        else
        {
            foreach (Artist artist in Model.ArtistData)
            {
                <tr>
                    <td>

                        @artist.Artist_Name
                    </td>
                    <td>

                        @artist.Artist_role
                    </td>
                    <td>

                        @artist.Artist_contact
                    </td>
                    <td>
                    </td>
                </tr>

            }

        }
    }


    

</table>

<a href="@Url.Action("Logout","Login")" class="btn btn-warning">Logout</a>

SecurityInAOMG/Views/Home/userView.cshtml
@model IEnumerable<SecurityInAOMG.Models.Artist>

@{
    Layout = "~/Views/Shared/_View.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>userView</title>
</head>
<body>

    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Artist_Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Artist_role)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Artist_contact)
            </th>
            <th></th>
        </tr>

        @foreach (System.Data.DataRow dr in ViewBag.data.Rows)
        {
            <tr>
                <td>

                    @dr["Artist_Name"]
                </td>
                <td>

                    @dr["Artist_role"]
                </td>
                <td>

                    @dr["Artist_contact"]
                </td>

            </tr>
        }

    </table>

    <a href="@Url.Action("Logout","Login")" class="btn btn-warning">Logout</a>
</body>
</html>