SecurityInAOMG/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.SqlClient;
using SecurityInAOMG.Models;

namespace SeurityASP.NET.Controllers
{
    public class LoginController : Controller
    {
        SqlConnection con = new db().con;
        SqlCommand cmd1 = new SqlCommand();
        SqlCommand cmd2 = new SqlCommand();
        SqlCommand cmd3 = new SqlCommand();
        SqlDataReader dr;
        SqlDataReader dr2;
        SqlDataReader dr3;
        // GET: Login
        public ActionResult Index()
        {
            if (Session["user"] != null)
            {
                Response.Redirect("https://www.google.com.vn/imghp?hl=vi");

            }

            return View();
        }

        public JsonResult CheckLogin(FormCollection Collection)
        {
            string uid = Collection["uid"];
            string pwd = Collection["password"];



            cmd1.Connection = con;
            cmd2.Connection = con;
            cmd3.Connection = con;

            con.Open();

            cmd1.CommandText = "select * from Users where username= @uid and password=@pwd  and roles=@roles ";
            cmd1.Parameters.AddWithValue("@uid", uid);
            cmd1.Parameters.AddWithValue("@pwd", pwd);
            cmd1.Parameters.AddWithValue("@roles", "admin");


            cmd2.CommandText = "select * from Users where username= @uid and password=@pwd  and roles=@roles ";
            cmd2.Parameters.AddWithValue("@uid", uid);
            cmd2.Parameters.AddWithValue("@pwd", pwd);
            cmd2.Parameters.AddWithValue("@roles", "user");

            cmd3.CommandText = "select * from Users where username= @uid and password=@pwd  and roles=@roles ";
            cmd3.Parameters.AddWithValue("@uid", uid);
            cmd3.Parameters.AddWithValue("@pwd", pwd);
            cmd3.Parameters.AddWithValue("@roles", "editor");





            dr = cmd1.ExecuteReader();
            dr2 = cmd2.ExecuteReader();
            dr3 = cmd3.ExecuteReader();


            JsonResult jr = new JsonResult();

            if (dr.Read())
            {

                Session["user"] = 1;
                Session.Timeout = 5;

                jr.Data = new
                {
                    status = "OK"
                };
                con.Close();

            }
            else if (dr2.Read())
            {
                Session["user"] = 2;
                Session.Timeout = 5;

                jr.Data = new
                {
                    status = "OK"
                };


            }

            else if (dr3.Read())
            {
                Session["user"] = 3;
                Session.Timeout = 5;

                jr.Data = new
                {
                    status = "OK"
                };


            }
            else
            {
                jr.Data = new
                {
                    status = "False"
                };
            }

            return Json(jr, JsonRequestBehavior.AllowGet);


        }


        public ActionResult Logout()
        {
            Session.Clear();//remove session
            return RedirectToAction("Index");
        }





    }
}

SecurityInAOMG/Controllers/ResgisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.SqlClient;
using SecurityInAOMG.Models;

namespace SecurityInAOMG.Controllers
{
    public class ResgisterController : Controller
    {
        // GET: Resgister
        SqlConnection con = new db().con;
        SqlCommand cmd = new SqlCommand();
     
        
        public ActionResult Resgister()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Resgister(UserAccount user)
        {

            con.Open();
            cmd.CommandText = "insert into Users  values(@userId,@username, @password, 'user') ";

            if (Session["user"] == null)
            {
                cmd.Parameters.AddWithValue("@userId", user.userId);
                cmd.Parameters.AddWithValue("@username", user.username);
                cmd.Parameters.AddWithValue("@password", user.password);
               
                cmd.Connection = con;
                cmd.ExecuteNonQuery();

                con.Close();

            }
            return View();

        }

        public ActionResult ResgisterForAdmin()
        {
            return View();
        }


        [HttpPost]
        public ActionResult ResgisterForAdmin(UserAccount user)
        {

            con.Open();
            cmd.CommandText = "insert into Users  values(@userId,@username, @password, 'admin') ";

            //if (Session["user"] == null)
            //{
            cmd.Parameters.AddWithValue("@userId", user.userId);
            cmd.Parameters.AddWithValue("@username", user.username);
            cmd.Parameters.AddWithValue("@password", user.password);


            cmd.Connection = con;
            cmd.ExecuteNonQuery();

            con.Close();

            //}
            return View();

        }

    }
}

SecurityInAOMG/Controllers/RolesController.cs
    using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SecurityInAOMG.Models;
using System.Data.SqlClient;

namespace SecurityInAOMG.Controllers
{
    public class RolesController : Controller
    {
        // GET: Roles
        SqlConnection con = new db().con;

        // GET: Group

        public ActionResult Index()
        {
            if (Session["user"] != null)
            {
                List<UseGroup> model = new db().GetUserGroup();
                return View(model);
            }
            else
            {
                return Redirect("https://localhost:44357/");
            }

        }

        public ActionResult Edit(int id)
        {
            List<UseGroup> userGroup = new db().GetUserGroup();
            var getId = userGroup.Single(m => m.Group_user_Id == id);

        

            return View(getId);
        }

        [HttpPost]
       public ActionResult Edit(UseGroup useGroup, int id)
        {

            SqlCommand cmd = new SqlCommand();


            List<UseGroup> userGroup = new db().GetUserGroup();
            var getId = userGroup.Single(m => m.Group_user_Id == id);

           

            con.Open();
          

            switch (useGroup.CheckedEdit)
            {
                case true:
                   

                        cmd.CommandText = "update Group_User set Editing='" + useGroup.Editing + "'  where Group_user_Id= " + getId.Group_user_Id + "";

                        cmd.Connection = con;
                        cmd.ExecuteNonQuery();
                
                        
                    
                       break;
                case false:
                   
                        cmd.CommandText = "update Group_User set Editing='Null'  where Group_user_Id= " + getId.Group_user_Id + "";

                        cmd.Connection = con;
                        cmd.ExecuteNonQuery();
                  
                      break;

            }

            switch (useGroup.CheckedDetail)
            {
                case true:

                        cmd.CommandText = "update Group_User set  Detail='" + useGroup.Detail + "'  where Group_user_Id= " + getId.Group_user_Id + "";

                        cmd.Connection = con;
                        cmd.ExecuteNonQuery();
                   
                       

                    
                    break;
                case false:
                   
                        cmd.CommandText = "update Group_User set Detail='Null'    where Group_user_Id= " + getId.Group_user_Id + "";

                        cmd.Connection = con;
                        cmd.ExecuteNonQuery();
                    
                   

                    

                    break;

            }

            switch (useGroup.CheckedDelete)
            {
                case true:
                   
                        cmd.CommandText = "update Group_User set  Deleting='" + useGroup.Deleting + "'  where Group_user_Id= " + getId.Group_user_Id + "";

                        cmd.Connection = con;
                        cmd.ExecuteNonQuery();
                  
                    

                   
                    break;
                case false:
                    

                        cmd.CommandText = "update Group_User set Deleting='Null'  where Group_user_Id= " + getId.Group_user_Id + "";

                        cmd.Connection = con;
                        cmd.ExecuteNonQuery();
                  
              

                    
                    break;

            }

            con.Close();



            return View();

        } 


    }
}

SecurityInAOMG/Views/Resgister/Resgister.cshtml
@model SecurityInAOMG.Models.UserAccount

@{
    ViewBag.Title = "Resgister";
    Layout = "~/Views/Shared/_View.cshtml";
}

<link rel="stylesheet" type="text/css" href="~/Content/TaoNhom.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">

<h2>Tạo Nhóm</h2>

<div class="buttonStyle">
    <button type="button " onclick="location.href='@Url.Action("Edit", "Roles")'">Quản lý nhóm </button>
    <button type="button" class="active">Tạo nhóm</button>
</div>

<hr class="hrtag">
<div class="container">
    <form>
        <div class="row">
            <div class="col-25">
                <label for="MaNhom">Mã nhóm <span style="color:red;">(*)</span></label>
            </div>
            <div class="col-75">
                <input type="text" id="MaNhom" name="MaNhom" placeholder="Mã nhóm...">
            </div>
        </div>
        <div class="row">
            <div class="col-25">
                <label for="TenNhom">Tên Nhóm <span style="color:red;">(*)</span></label>
            </div>
            <div class="col-75">
                <input type="text" id="TenNhom" name="TenNhom" placeholder="Tên Nhóm..">
            </div>
        </div>


    </form>

</div>

<div class="buttonStyle2">
    <button type="button ">Thêm</button>
    <button type="button">Làm mới</button>
</div>

SecurityInAOMG/Views/Resgister/ResgisterForAdmin.cshtml
@model SecurityInAOMG.Models.UserAccount

@{
    ViewBag.Title = "Resgister";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ResgisterSomething</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>UserAccount</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.userId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.userId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.userId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Home", "Index", "Login")
</div>